config/routes.rb
Rails.application.routes.draw do
  resources :people, only: :index

  root 'people#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person

  validates :street, :city, :country, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include Filterable

  self.abstract_class = true
end

app/models/concerns/filterable.rb
# frozen_string_literal: true

# Filtering functionality for ActiveRecord models
# enables fuzzy search on any column, including relations
#
# Usage:
# ModelClass.filtered('query', %w[column_1, column_2, association_column1])
module Filterable
  extend ActiveSupport::Concern

  included do
    def self.filtered(pattern, columns)
      ::Services::FuzzySearch.new(self).find_records(pattern, columns)
    end
  end
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :workplace, optional: true

  has_many :addresses

  validates :first_name, :last_name, presence: true
  validates :age, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
end

app/models/workplace.rb
class Workplace < ApplicationRecord
  has_many :people
  has_many :addresses, through: :people

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  FILTERABLE_COLUMNS = %w[
    first_name
    last_name
    age
    addresses_street
    addresses_city
    addresses_country
    workplace_name
  ].freeze

  def index
    assign_people

    respond_to do |format|
      format.js
      format.html
    end
  end

  private

  def assign_people
    @people = if params[:filter]
                filtered_people
              else
                unfiltered_people
              end
  end

  def filtered_people
    Person
      .filtered(params[:filter], FILTERABLE_COLUMNS)
      .includes(:workplace)
      .includes(:addresses)
      .order(:created_at)
      .page(params[:page])
      .per(params[:per])
  end

  def unfiltered_people
    Person
      .includes(:workplace)
      .includes(:addresses)
      .order(:created_at)
      .page(params[:page])
      .per(params[:per])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilterableModels</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_table.html.erb
<table border="1">
  <thead>
    <tr>
      <th>Company</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Age</th>
      <th>Addresses</th>
    </tr>
  </thead>
  <tbody>
    <% people.each do |person| %>
      <tr>
        <td><%= person.workplace.name %></td>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.age %></td>
        <td>
          <% person.addresses.each do |address| %>
            <ul>
              <li><%= address.street %></li>
              <li><%= address.city %></li>
              <li><%= address.country %></li>
            </ul>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/index.html.erb
<div id="filter-form">
  <%= form_tag(people_path, method: :get, remote: true) do %>
      <%= label_tag(:filter, 'Filter for:') %>
      <%= text_field_tag(:filter) %>
      <%= submit_tag('Filter') %>
  <% end %>
</div>
<div id="people">
  <%= render('people/table', people: @people) %>
</div>
<div id="paginator">
  <%= paginate(@people, remote: true) %>
</div>

app/views/people/index.js.erb
document.getElementById('people').innerHTML = "<%= escape_javascript(render('people/table', people: @people)) %>";
document.getElementById('paginator').innerHTML = "<%= escape_javascript(paginate(@people, remote: true)) %>";